define({
  "COMMAND_NAME": "Extrahieren",
  "DIALOG_ERROR_NO_SELECTION": "Kein Code zum Extrahieren selektiert!",
  "DIALOG_ERROR_UNSUPPORTED_FILE": "Nicht ünterstütztes Dateiformat: Dateiformat muss Javascript sein!",
  "DIALOG_ERROR_TITLE": "Fehler während des Extrahierens",
  "DIALOG_INPUT_PLACEHOLDER": "extrahiert",
  "DIALOG_LABEL_FUNCTION": "Funktion",
  "DIALOG_LABEL_VARIABLE": "Variable",
  "DIALOG_LABEL_EXTRACT_TO": "Extrahieren als",
  "DIALOG_LABEL_NEW_NAME": "Neuer Name",
  "DIALOG_LABEL_REPLACE": "Ersetzen",
  "DIALOG_LABEL_TEXT": "Ausgewählte Sprache",
  "DIALOG_LABEL_ALL": "Alle Instanzen",
  "DIALOG_LABEL_SELECT": "Instanzen auswählen",
  "DIALOG_TITLE": "Extrahieren",
  "PROMPT_LABEL_INSTANCE": "Instanzen",
  "PROMPT_LABEL_YES": "Ja",
  "PROMPT_LABEL_NO": "Nein",
  "PROMPT_LABEL_YES_TO_REST": "Ja zum Rest",
  "PROMPT_LABEL_NO_TO_REST": "Nicht Mehr",
  "PROMPT_TITLE": "Diese Instanz extrahieren?"
});
